### ISSUE TITLE
FTBFS on Ubuntu 18.04

### ISSUE THREAD

**Issue by rzr** [intel/iotivity-node#172]
I think that was fixed in master or 1.4-rel

Alternative would be to disable BT ?

```
Compiling resource/csdk/connectivity/src/bt_le_adapter/linux/client.o
In file included from /usr/include/glib-2.0/gobject/gbinding.h:29:0,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from resource/csdk/connectivity/src/bt_le_adapter/linux/context.h:27,
                 from resource/csdk/connectivity/src/bt_le_adapter/linux/client.h:22,
                 from resource/csdk/connectivity/src/bt_le_adapter/linux/client.c:19:
resource/csdk/connectivity/src/bt_le_adapter/linux/client.c: In function 'CAGattClientSetupCharacteristics':
/usr/include/glib-2.0/gobject/gobject.h:512:32: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
 #define g_object_ref(Obj)      ((__typeof__(Obj)) (g_object_ref) (Obj))
                                ^
resource/csdk/connectivity/src/bt_le_adapter/linux/client.c:249:37: note: in expansion of macro 'g_object_ref'
             gpointer * const chrc = g_object_ref(characteristic);
                                     ^~~~~~~~~~~~
cc1: all warnings being treated as errors
scons: *** [resource/csdk/connectivity/src/bt_le_adapter/linux/client.o] Error 1
scons: building terminated because of errors.
csdk.target.mk:13: recipe for target 'iotivity-installed' failed
make: *** [iotivity-installed] Error 2
make: Leaving directory '/tmp/node_modules/iotivity-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/node_modules/iotivity-node
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iotivity-node"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
```

**Comment by gabrielschulhof** [comment]
@rzr I'm trying to make 1.4.0-RC2 work, but I'm having trouble setting up the oic_svr_db.dat files - it seems they got broken again.

**Comment by rzr** [comment]
well actually I havent check since 1.3.1 is problem reproductible with iotivity's examples ?
If yes it would help to report upstream.

**Comment by gabrielschulhof** [comment]
@rzr I reproduced the compilation error locally. Which commit fixes it? git blame on master points to [97927b79](https://gerrit.iotivity.org/gerrit/gitweb?p=iotivity.git;a=commit;h=97927b795429ddaaaf7d32ab47f58be3577fef86) but that's a large commit introducing the whole chunk of code in which the error occurs. Is there a better commit?

**Comment by rzr** [comment]
Does I-node supports BT/BLE ? if not maybe we can just use IP transport ?

**Comment by gabrielschulhof** [comment]
@rzr iotivity-node is not transport-specific. It simply exposes the C SDK. It doesn't turn on or off any transports when it builds iotivity.

**Comment by LaszloLango** [comment]
I've got the same issue. Any working fix for it?
